### ISSUE TITLE
Map out project milestones

### ISSUE THREAD

**Issue by JBercich** [JBercich/traffic-ai#2]
The final sections of this project are prone to change...

Python

- [ ] Implement a simulation environment for traffic
- [ ] Implement an appropriate DQN training pipeline
- [ ] Tweak the model to get reasonably good results
- [ ] Visualise results

C++

- [ ] Replicate the model and simulation
- [ ] (?) Visualise the simulation
- [ ] (?) Visualise the iterations of the training environment
- [ ] (?) ...
